---
title: "Учимся Quarto и работе на Github"
---

## О Quarto

Quarto --- это бесплатная открытая публикационная система основаная на Pandoc.

-   Позволяет создавать проекты в Python, R, Julia, и Observable
-   Для создания документов используется разметка markdown (которую мы изучим)
-   Позволяет создавать документы, отчеты, презентации, сайты, блоги, книги в HTML, PDF, MS Word, ePub, и некоторых других форматах.
-   Включает в себя расширения markdown разметки, которые позволяют писать формулы, цитировать литературу, обращаться к фрагментам текста, размещать графикик и т. п.

Мы будем создавать на quarto веб-сайт.

## Github

Github --- это крупнейшая платформа для разработки софта. В ее основе лежит система версионирования git, которая отслеживает и фиксирует изменения. Нам она интересна лишь одним: она ставит преграды на пути случайного уничтожения чужой работы.

Мы будем использовать github как бесплатную платформу для хостинга нашего сайта, но это совершенно не обязательно, полученные html можно передвигать куда угодно.

## Markdown разметка

Заголовки разного уровня -- задаются количеством `#` перед текстом. Еще нужно оставлять пустые строки перед и после заголовка.

### Базовое форматирование

- `**жирное**` -- **жирное**
- `*курсив*` -- *курсив*
- поменять цвет
- `[подчеркивание]{.underline}` -- [подчеркивание]{.underline}
- `~~зачеркивание~~` ~~зачеркивание~~
- минус `-` -
- дефис `--` --
- тере `---` ---

### Кусочки

Чтобы вставить цитату, нужно перед строчкой поставить `>`

> Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата Большая цитата 

